import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ShieldCheck, Clock, Trash2, Database, Eye, Lock } from "lucide-react";

export const metadata = {
  title: "Privacy Policy — Email Footprint",
  description: "How Email Footprint handles your data. Session-only, no persistent storage.",
};

const sections = [
  {
    id: "what-we-collect",
    icon: <Database className="w-4 h-4" />,
    title: "What we collect",
    content: `When you search for an email address, we temporarily hold it in your browser's session storage to run the lookup and display results. We do not send your email to any third-party analytics providers, advertising networks, or data brokers. The email is used solely to query breach datasets and return results to your browser.`,
  },
  {
    id: "data-retention",
    icon: <Clock className="w-4 h-4" />,
    title: "Data retention",
    content: `Your email address and any associated results are stored only in your browser's sessionStorage for the duration of your session, with a maximum TTL of 5 minutes. After 5 minutes of inactivity, the data is automatically cleared. Closing the browser tab or clicking "Clear session" also removes all data immediately. We do not store any information server-side beyond the duration of individual API requests.`,
  },
  {
    id: "how-results-are-generated",
    icon: <Eye className="w-4 h-4" />,
    title: "How results are generated",
    content: `Results are generated by cross-referencing your email with publicly available breach datasets, including feeds similar to Have I Been Pwned. All results are clearly labeled as inferences — a "Possible" result means the email appeared in breach data associated with a service, which does not confirm an active account. We never make definitive claims about account existence unless verified by the account holder.`,
  },
  {
    id: "passwords",
    icon: <Lock className="w-4 h-4" />,
    title: "Passwords",
    content: `This service never requests, stores, or transmits passwords. If you are prompted for a password anywhere during this flow, something is wrong. The verification step uses a one-time code sent to your email — not a password.`,
  },
  {
    id: "delete",
    icon: <Trash2 className="w-4 h-4" />,
    title: "Deleting your session",
    content: `You can clear all session data at any time by clicking the "Clear session" button in the navigation bar. This removes all email addresses, results, and session tokens stored in your browser. Because we do not store data server-side persistently, there is nothing else to delete. If you have questions or concerns, please contact us via the GitHub repository.`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-1 max-w-2xl mx-auto w-full px-4 py-12">
        <div className="space-y-8">
          {/* Header */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-xl bg-brand-indigo/10 flex items-center justify-center">
                <ShieldCheck className="w-4 h-4 text-brand-indigo" aria-hidden="true" />
              </div>
              <h1 className="font-display font-bold text-2xl text-brand-text">Privacy Policy</h1>
            </div>
            <p className="text-sm text-brand-sub font-body leading-relaxed">
              Email Footprint is designed with privacy as a first principle. Here is exactly how we
              handle your data — in plain language, not legal jargon.
            </p>
            <div className="inline-flex items-center gap-2 bg-green-50 border border-green-200 rounded-xl px-4 py-2">
              <ShieldCheck className="w-3.5 h-3.5 text-brand-green" aria-hidden="true" />
              <span className="text-xs font-semibold text-green-700 font-body">
                No accounts · No persistent storage · Session-only
              </span>
            </div>
          </div>

          {/* Privacy snippet */}
          <blockquote className="bg-indigo-50 border-l-4 border-brand-indigo rounded-r-2xl px-5 py-4">
            <p className="text-sm text-indigo-800 font-body leading-relaxed italic">
              &ldquo;We do not store your email or results beyond this session. All data is held in
              your browser only and automatically cleared after 5 minutes of inactivity or when you
              click &lsquo;Clear session&rsquo;. Results are inferences from public breach data —
              not confirmations. This app never requests your password.&rdquo;
            </p>
          </blockquote>

          {/* Sections */}
          <div className="space-y-4">
            {sections.map((s) => (
              <section
                key={s.id}
                id={s.id}
                className="bg-white rounded-2xl border border-brand-border p-6 space-y-3"
              >
                <div className="flex items-center gap-2.5">
                  <span className="text-brand-indigo" aria-hidden="true">{s.icon}</span>
                  <h2 className="font-display font-semibold text-brand-text text-base">{s.title}</h2>
                </div>
                <p className="text-sm text-brand-sub font-body leading-relaxed">{s.content}</p>
              </section>
            ))}
          </div>

          {/* Last updated */}
          <p className="text-xs text-brand-sub/60 font-mono text-center">
            Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
